// -*- tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*-
// vi: set et ts=4 sw=2 sts=2:
#ifndef DUNE_GEOMETRY_QUADRATURE_{{ domain |> upper }}_HH
#define DUNE_GEOMETRY_QUADRATURE_{{ domain |> upper }}_HH

#ifndef DUNE_INCLUDING_IMPLEMENTATION
#error This is a private header that should not be included directly.
#error Use #include <dune/geometry/quadraturerules.hh> instead.
#endif

#include <dune/geometry/quadraturerules/numberfromstring.hh>


namespace Dune {

  /*************************************************************
   * Quadraturerule for {{ domain }}
   * Generated by FiniteElementQuadratureRules.jl on {{ date }}
   *************************************************************/

  /** \brief Quadrature rules for {{ domain }}
      \ingroup Quadrature
   */
  template<typename ct, int dim>
  class {{ region }}QuadratureRule;

  /** \brief Quadrature rules for {{ region }}
      \ingroup Quadrature
   */
  template<typename ct>
  class {{ region }}QuadratureRule<ct, {{ dim }}> : public QuadratureRule<ct, {{ dim }}>
  {
  public:
    /** \brief The highest quadrature order available */
    enum { highest_order = {{ maxdegree }} };

  private:
    friend class QuadratureRuleFactory<ct, {{ dim }}>;
    {{ region }}QuadratureRule (int p);
    ~{{ region }}QuadratureRule() {}
  };

  template<typename ct>
  {{ region }}QuadratureRule<ct, {{ dim }}>::{{ region }}QuadratureRule(int order)
    : QuadratureRule<ct, {{ dim }}>(GeometryTypes::{{ domain |> lower }})
  {
    using Base = QuadratureRule<ct, {{ dim }}>;
    using Vector = typename Base::value_type::Vector;

    switch (order)
    {
    {%- for rule in rules %}
      case {{ rule["degree"] }}:
      {%- if haskey(rule, "coordinates") && length(rule["coordinates"]) > 0 %}
      {%- let coordinates = rule["coordinates"], weights = rule["weights"] %}
      {%- let npoints = length(coordinates) %}
        // dim = {{ dim }}, order = {{ rule["degree"] }}, npoints = {{ npoints }}, properties = {{ rule["properties"] }}
        {%- if haskey(rule, "reference") %}
        // Source: {{ rule["reference"] }}
        {%- end %}
        this->delivered_order = {{ rule["degree"] }};
        this->resize({{ npoints }});
        {%- for (i,p) in enumerate(coordinates) %}
        {%- let plast = last(p) %}
        (*this)[{{i}}] = {
          Vector{ {%- for j in 1:length(p)-1 %}
            DUNE_NUMBER_FROM_STRING(ct, {{ p[j] }}),
            {%- end %}
            DUNE_NUMBER_FROM_STRING(ct, {{ plast }}) },
          DUNE_NUMBER_FROM_STRING(ct, {{ weights[i] }})
          };
        {%- end %}
        {%- end %}
        break;
      {%- end %}
      {%- end %}
      {%- end %}
    {%- end %}
      default:
        DUNE_THROW(QuadratureOrderOutOfRange,
                  "QuadratureRule for order " << order << " and GeometryType "
                                              << this->type() << " not available");
    }
  }

} // end namespace Dune

#endif // DUNE_GEOMETRY_QUADRATURE_{{ domain |> upper }}_HH
