using StaticArrays: SVector

struct {{ domain }}QuadRule{ T<:Real, Point<:AbstractVector{T} }
  degree::Int
  points::Vector{Point}
  weights::Vector{T}
end

#==
 Generated by FiniteElementQuadratureRules.jl on {{ date }}
==#

{{ domain }}QuadRule(degree::Val{d}) where d = {{ domain }}QuadRule(Float64, degree)
{{ domain }}QuadRule(degree::Integer) = {{ domain }}QuadRule(Float64, Val{degree}())
{{ domain }}QuadRule(::Type{T}, degree::Integer) = {{ domain }}QuadRule(T, Val{degree}())


{%- for (degree,rule) in enumerate(rules) %}
{%- if ismissing(rule) %}
{{ domain }}QuadRule(::Type{T}, ::Val{ {{ degree }} }) where T = {{ domain }}QuadRule(T, Val{ {{ degree+1 }} }())
{%- else %}
{%- let coordinates = rule["coordinates"], weights = rule["weights"] %}

# Source: {{ rule["reference" ] }}
function {{ domain }}QuadRule(::Type{T}, degree::Val{ {{ degree }} }) where {T<:Real}
  {{ domain }}QuadRule({{ degree }},
  #= points =# [
  {%- for p in coordinates %}
    {%- let len = length(p) %}
    SVector{ {{ len }}, T }((
      {%- for p_i in p %}
      parse(T, "{{ p_i }}"),
      {%- end %} )),
    {%- end %}
  {%- end %}
  ],
  #= weights =# T[
  {%- for w in weights %}
    parse(T, "{{ w }}"),
  {%- end %}
  ])
end
{%- end %}
{%- end %}
{%- end %}
