// -*- tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*-
// vi: set et ts=4 sw=2 sts=2:
// SPDX-FileCopyrightInfo: Copyright © DUNE Project contributors, see file LICENSE.md in module root
// SPDX-License-Identifier: LicenseRef-GPL-2.0-only-with-DUNE-exception
#ifndef DUNE_GEOMETRY_QUADRATURE_LINE_HH
#define DUNE_GEOMETRY_QUADRATURE_LINE_HH

#ifndef DUNE_INCLUDING_IMPLEMENTATION
#error This is a private header that should not be included directly.
#error Use #include <dune/geometry/quadraturerules.hh> instead.
#endif

#include <dune/geometry/quadraturerules/numberfromstring.hh>


namespace Dune {

  /*************************************************************
   * Quadraturerule for Line
   * Generated by FiniteElementQuadratureRules.jl on 2026-02-25
   *************************************************************/

  /** \brief Quadrature rules for Line
      \ingroup Quadrature
   */
  template<typename ct, int dim>
  class CubeQuadratureRule;

  /** \brief Quadrature rules for Cube
      \ingroup Quadrature
   */
  template<typename ct>
  class CubeQuadratureRule<ct, 1> : public QuadratureRule<ct, 1>
  {
  public:
    /** \brief The highest quadrature order available */
    enum { highest_order = 0 };

  private:
    friend class QuadratureRuleFactory<ct, 1>;
    CubeQuadratureRule (int p);
    ~CubeQuadratureRule() {}
  };

  template<typename ct>
  CubeQuadratureRule<ct, 1>::CubeQuadratureRule(int order)
    : QuadratureRule<ct, 1>(GeometryTypes::line)
  {
    using Base = QuadratureRule<ct, 1>;
    using Vector = typename Base::value_type::Vector;

    switch (order)
    {
      case 0:
      default:
        DUNE_THROW(QuadratureOrderOutOfRange,
                  "QuadratureRule for order " << order << " and GeometryType "
                                              << this->type() << " not available");
    }
  }

} // end namespace Dune

#endif // DUNE_GEOMETRY_QUADRATURE_LINE_HH
