// -*- tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*-
// vi: set et ts=4 sw=2 sts=2:
// SPDX-FileCopyrightInfo: Copyright © DUNE Project contributors, see file LICENSE.md in module root
// SPDX-License-Identifier: LicenseRef-GPL-2.0-only-with-DUNE-exception
#ifndef DUNE_GEOMETRY_QUADRATURE_POINT_HH
#define DUNE_GEOMETRY_QUADRATURE_POINT_HH

#ifndef DUNE_INCLUDING_IMPLEMENTATION
#error This is a private header that should not be included directly.
#error Use #include <dune/geometry/quadraturerules.hh> instead.
#endif

#include <dune/geometry/quadraturerules/numberfromstring.hh>


namespace Dune {

  /*************************************************************
   * Quadraturerule for Point
   * Generated by FiniteElementQuadratureRules.jl on 2026-02-25
   *************************************************************/

  /** \brief Quadrature rules for Point
      \ingroup Quadrature
   */
  template<typename ct, int dim>
  class PointQuadratureRule;

  /** \brief Quadrature rules for Point
      \ingroup Quadrature
   */
  template<typename ct>
  class PointQuadratureRule<ct, 0> : public QuadratureRule<ct, 0>
  {
  public:
    /** \brief The highest quadrature order available */
    enum { highest_order = 0 };

  private:
    friend class QuadratureRuleFactory<ct, 0>;
    PointQuadratureRule (int p);
    ~PointQuadratureRule() {}
  };

  template<typename ct>
  PointQuadratureRule<ct, 0>::PointQuadratureRule(int order)
    : QuadratureRule<ct, 0>(GeometryTypes::point)
  {
    using Base = QuadratureRule<ct, 0>;
    using Vector = typename Base::value_type::Vector;

    switch (order)
    {
      case 0:
      default:
        DUNE_THROW(QuadratureOrderOutOfRange,
                  "QuadratureRule for order " << order << " and GeometryType "
                                              << this->type() << " not available");
    }
  }

} // end namespace Dune

#endif // DUNE_GEOMETRY_QUADRATURE_POINT_HH
